# Generated by Django 5.2.3 on 2025-06-26 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_surname", models.CharField(max_length=20)),
                ("second_surname", models.CharField(max_length=20)),
                ("first_name", models.CharField(max_length=20)),
                ("other_names", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Colombia", "Colombia"),
                            ("Estados Unidos", "Estados Unidos"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id_type", models.CharField(max_length=30)),
                ("id_number", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=300, unique=True)),
                ("entry_date", models.DateField()),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("Administración", "Administración"),
                            ("Financiera", "Financiera"),
                            ("Compras", "Compras"),
                            ("Infraestructura", "Infraestructura"),
                            ("Operación", "Operación"),
                            ("Talento Humano", "Talento Humano"),
                            ("Servicios Varios", "Servicios Varios"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(default="Activo", editable=False, max_length=10),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
            options={
                "unique_together": {("id_type", "id_number")},
            },
        ),
    ]
