# Generated by Django 5.2.3 on 2025-06-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("Cédula de Ciudadanía", "Cédula de Ciudadanía"),
                    ("Cédula Extranjera", "Cédula Extranjera"),
                    ("Pasaporte", "Pasaporte"),
                    ("Permiso Especial", "Permiso Especial"),
                ],
                max_length=30,
            ),
        ),
    ]
